Ufostranky/Controllers/ApiControllers/ArticleController.cs
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using Ufostranky.Models;

namespace Ufostranky.Controllers
{
    public class ArticleController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: api/Article
        public IQueryable<Article> GetArticles()
        {
           return db.Articles;
        }

        // GET: api/Article/5
        [ResponseType(typeof(Article))]
        public async Task<IHttpActionResult> GetArticle(int id)
        {
            Article article = await db.Articles.FindAsync(id);
            if (article == null)
            {
                return NotFound();
            }
            
            return Ok(article);
        }

        // PUT: api/Article/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutArticle(int id, Article article)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != article.Id)
            {
                return BadRequest();
            }

            db.Entry(article).State = EntityState.Modified;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ArticleExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw new DbUpdateException("sry what? how?");
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Article
        [ResponseType(typeof(Article))]
        public async Task<IHttpActionResult> PostArticle(Article article)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Articles.Add(article);
            await db.SaveChangesAsync();

            return CreatedAtRoute("DefaultApi", new { id = article.Id }, article);
        }

        // DELETE: api/Article/5
        [ResponseType(typeof(Article))]
        public async Task<IHttpActionResult> DeleteArticle(int id)
        {
            Article article = await db.Articles.FindAsync(id);
            if (article == null)
            {
                return NotFound();
            }

            db.Articles.Remove(article);
            await db.SaveChangesAsync();

            return Ok(article);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool ArticleExists(int id)
        {
            return db.Articles.Count(e => e.Id == id) > 0;
        }
    }
}

Ufostranky/Controllers/MorseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ufostranky.Controllers
{
    public class MorseController : Controller
    {
        // GET: Morse
        public ViewResult Index()
        {
            return View();
        }
    }
}

Ufostranky/Controllers/SquareStuffController.cs
using System;
using System.Web.Mvc;
using Ufostranky.Models;

namespace Ufostranky.Controllers
{
    public class SquareStuffController : Controller
    {
        // GET: SquareStuff
        public ViewResult Index()
        {
            SquareStuff squares = new SquareStuff();

            return View(squares);
        }
    }
}

Ufostranky/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Richard Kubný" />
    <meta name="description" content="Ufopages full of aliens, programming, logic games, morse code, and other stupid shit for education" />

    <link rel="shortcut icon" type="image/x-icon" href="@Url.Content("~/Images/favicon.ico")" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", false)
</head>
<body>
    @{ Html.RenderPartial("~/Views/Shared/_LoginPartial.cshtml"); }
    <section id="mainSection">
        <nav id="mainMenu">
            <ul>
                <li>
                    <div id="home" class="menuDiv">
                        <span id="spanInHome" class="menuSpan">
                            @Html.ActionLink("Home", "Index", "Home")
                        </span>
                    </div>
                </li>
                <li>
                    <div class="relative">
                        <div id="guestbook" class="menuDiv">
                            <span id="spanInGuestDiv" class="menuSpan">
                                @Html.ActionLink("Guestbook", "Index", "Guestbook", null, htmlAttributes: new { @class = "center" })
                            </span>
                        </div>
                    </div>
                </li>
                <li>
                    <div id="squaresAndShit" class="menuDiv">
                        @for (byte i = 1; i <= 15; ++i)
                        {
                            string id = "s" + i;
                            <div id="@id" class="absoluteSquare"></div>
                        }

                        @Html.ActionLink(" ", "Index", "SquareStuff", null, htmlAttributes: new { @id = "linkSq" })
                    </div>
                </li>
                <li>
                    <div id="morseDiv" class="menuDiv">
                        <span id="morse">A</span>
                        @Html.ActionLink(" ", "Index", "Morse")
                    </div>                  
                </li>

                @if (User.IsInRole("admin")) { 
                <li>
                    <div class="menuDiv">
                        @Html.ActionLink("Programming", "Index", "ProgrammingLanguage")
                    </div>
                </li>
                <li>
                    <div class="menuDiv">
                        @Html.ActionLink("kuscak", "Index", "Article") @* change controller - article == api *@
                    </div>
                </li>
                }
                
            </ul>
        </nav>

        <div id="clearer"></div>
        <section id="content">
            @RenderBody()
        </section>
    </section>

    <footer id="mainFooter">
        <p>&copy; @DateTime.Now.Year - PHP používají divoši</p>
    </footer> 
    @Scripts.Render("~/bundles/everypage")
    @RenderSection("scripts", required: false)
</body>
</html>